config/routes.rb
Rails.application.routes.draw do
  get 'routes/index'

  get 'routes/show'

  root "artworks#index"

  get 'pictures/new'
  get 'pictures/show'
  get 'pictures/create'
  get 'pictures/destroy'



  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show] do
      member do
        put "validated", to: "admin#artists_validated"
      end
  end

	resources :artworks do
    member do
      put "validated", to: "admin#artwork_validated"
    end
  end
	resources :searches
  resources :routes
	resources :pictures do
    member do
      put "like", to: "pictures#upvote"
      put 'unlike', to: "pictures#downvote"
    end
  end

	get 'admin', to: "admin#adminboard", as: "admin"
  get 'admin/artwork-moderation', to: "admin#artwork_moderation", as: "art_moderation"
  get 'admin/new-pictures-moderation', to: "admin#new_pictures_moderation", as: "new_pic_moderation"
  get 'admin/signaled-pictures-moderation', to: "admin#signaled_pictures_moderation", as: "signaled_pic_moderation"
  get 'admin/artists-moderation', to: "admin#artists_moderation", as: "artists_moderation"

	get 'users/:id', to: "users#show", as: "user_profile"
  put 'admin/validates_artist/:id', to: "admin#validates_artist", as: "validates_artist"
  put 'admin/unvalidate_artist/:id', to: "admin#unvalidate_artist", as: "unvalidate_artist"


  get 'artworks/show_small/:id', to: "artworks#show_small"
  get 'artworks/new/:lat/:long', to: "arwtorks#new"
  get 'artworks/claimed/:id', to: "artworks#claim_artwork", as: "claim_artwork"

  get 'pictures/signaled/:id', to: "pictures#signal", as: "signal_picture"
  get 'pictures/moderate/:id', to: "pictures#moderate", as: "moderate_picture"
  get 'pictures/unsignal/:id', to: "pictures#unsignal", as: "unsignal_picture"

  get 'menu/camera_kit'
  get 'menu/technics'
  get 'menu/propos'


end

app/views/admin/adminboard.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), user_path(current_user) %> </li>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>
<div class="body-container">
  <div class="admin_menu">
    <%= link_to "Modération des oeuvres", art_moderation_path  %>
    <%= link_to "Modération des nouvelles photos", new_pic_moderation_path  %>
    <%= link_to "Photos signalées", signaled_pic_moderation_path  %>
    <%= link_to "Artistes en cours de modération", artists_moderation_path  %>
  </div>
</div>

app/views/admin/artists_moderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), admin_path %> </li>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Liste des utilisateurs ayant fait une demande de statut "Artiste" :
    <br>
    <table>
      <tr>
        <th>ID</th>
        <th>Pseudo</th>
        <th>Email</th>
        <th>Ville</th>
        <th>Oeuvre(s) sur la(les)quelle(s) <br>la demande a été effectuée </th>
      </tr>
      <br>
      <% @pending_users.each do |user| %>
          <tr>
              <td><%= user.id %></td>
              <td><%= user.pseudo %></td>
              <td><%= user.email %></td>
              <td><%= user.city %></td>
              <td><% user.created_artworks.each do |artwork| %>
                <%= artwork.id %>
                <% end %>
              </td>
              <td>
                <% if user.artist == false %>
                  <%= link_to content_tag(:i, nil, class: 'far fa-thumbs-up', alt:'Valider cet artiste'), validates_artist_path(user), method: :put %>
                <% else %> OK
                <% end %>
              </td>

          </tr>

      <% end %>
    </table>
    <br>
    Liste des artistes validés :
    <br><br>
    <table>
      <tr>
        <th>ID</th>
        <th>Pseudo</th>
        <th>Email</th>
        <th>Ville</th>
        <th>Oeuvres créées par l'artiste</th>
        <th>Retrait statut</th>

      </tr>
      <% @validated_users.each do |user| %>
          <tr>
              <td><%= user.id %></td>
              <td><%= user.pseudo %></td>
              <td><%= user.email %></td>
              <td><%= user.city %></td>
              <td><% user.created_artworks.each do |artwork| %>
                <%= artwork.id %>
                <% end %>
              </td>
              <td>
                <% if user.artist == true %>
                  <%= link_to content_tag(:i, nil, class: 'far fa-thumbs-down', alt:'Retirer le statut artiste'), unvalidate_artist_path(user), method: :put %>
                <% else %> N'est pas artiste
                <% end %>
              </td>
          </tr>

      <% end %>
    </table>
  </div>
</div>

app/views/admin/artwork_moderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), admin_path %> </li>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des oeuvres :
    <br>

    <table>
      <tr>
        <th>ID</th>
        <th>Image</th>
        <th>Artiste</th>
        <th>Technique</th>
        <th>Modifications</th>
      </tr>
      <br>
      <% @artworks.each do |artwork| %>
          <tr>
              <td><%= artwork.id %></td>
              <td>
                <% if !artwork.pictures.first.nil? %>
                  <%= cl_image_tag artwork.pictures.first.img_url_url,:width => 200, :crop => :fill, :secure => true%>
                <% else %>
                  Pas de photo
                <% end %>
              </td>
              <td>
                <% if !artwork.artist.nil? %>
                    <%= artwork.artist %><br>
                    <% if !artwork.artists.nil? %>
                      <% artwork.artists.each do |artist| %>
                        <%= link_to artist.pseudo, artist %><br>
                      <% end %>
                    <% else %>
                      Pas d'artiste
                    <% end %>
                <% else %>
                  <% if !artwork.artists.nil? %>
                    <% artwork.artists.each do |artist| %>
                      <%= link_to artist.pseudo, artist %><br>
                    <% end %>
                  <% else %>
                    Pas d'artiste
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= artwork.style %>
              </td>
              <td>
                <%= form_tag artwork_path(artwork), method: :put do  %>
                  <%= label_tag 'Technique :' %><%= text_field_tag(:style, artwork.style) %>
                  <button type="submit" class="btn btn-primary">
                    <i class="fas fa-check-circle"></i>
                  </button>
                <% end %>
                  <%= form_tag artwork_path(artwork), method: :put do  %>
                  <%= label_tag 'Artiste :' %><%= select_tag 'artists', options_from_collection_for_select(User.where(artist:true).all, "id", "pseudo"), prompt: "Ajouter un artiste" %>
                  <button type="submit" class="btn btn-primary">
                    <i class="fas fa-check-circle"></i>
                  </button>
                <% end %>
              </td>
              <td>
                <% if artwork.moderated == false %>
                  <%= link_to content_tag(:i, nil, class: 'far fa-thumbs-up', alt:'Valider cette oeuvre'), validated_artwork_path(artwork), method: :put %>
                <% else %> OK
                <% end %>
              </td>
              <td><%= link_to content_tag(:i, nil, class: 'far fa-image', alt:'Modifier cette oeuvre'), artwork %>
              </td>
              <td><%= link_to content_tag(:i, nil, class: 'fas fa-trash-alt', alt:'Supprimer cette oeuvre'), artwork, method: :delete %>
              </td>
          </tr>

      <% end %>
    </table>
  </div>
</div>

app/views/admin/artworkmoderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), url_for(:back) %> </li>
    </li>
    <div class="header_title">
      <div class="header_title_logo"></div>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des oeuvres :
  </div>
</div>

app/views/admin/new_pictures_moderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), admin_path %> </li>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li></li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des nouvelles photos :
    <br>
    <table>
      <tr>
        <th>ID</th>
        <th>Image</th>
        <th>Utilisateur</th>
        <th>Modération</th>
      </tr>
      <br>
      <% @pictures_not_validated.each do |picture| %>
      <tr>
        <td><%= picture.id %></td>
        <td>
          <%= cl_image_tag picture.img_url_url,:width => 200, :crop => :fill, :secure => true%>
        </td>
        <td><%= picture.user.id %></td>
        <td>
          <% if picture.artwork.pictures.count == 1 %>
            <%= link_to content_tag(:i, nil, class: 'fas fa-trash-alt'), @artwork, data: { confirm: "Attention la suppression de cette photo entrainera la suppression de l'oeuvre !" }, method: :delete %>
          <% else %>
            <%= link_to content_tag(:i, nil, class: 'fas fa-trash-alt'), picture_path(picture), data: { confirm: "Etes-vous sûr(e) ?" }, method: :delete %>
          <% end %>
          <%= link_to content_tag(:i, nil, class: 'far fa-thumbs-up'), moderate_picture_path(picture) %>
          </td>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/newpicturesmoderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), url_for(:back) %> </li>
    </li>
    <div class="header_title">
      <div class="header_title_logo"></div>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des dernières images ajoutées :
  </div>
</div>

app/views/admin/signaled_pictures_moderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), admin_path %> </li>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des photos signalées
    <br>
    <table>
      <tr>
        <th>ID</th>
        <th>Image</th>
        <th>Photographe</th>
        <th>Modération</th>
      </tr>
      <br>
      <% @signaled_pictures.each do |picture| %>
      <tr>
        <td><%= picture.id %></td>
        <td>
          <%= cl_image_tag picture.img_url_url,:width => 200, :crop => :fill, :secure => true%>
        </td>
        <td><%= picture.user.id %> - <%= picture.user.pseudo %> (<%= picture.user.firstname %> <%= picture.user.name%>)</td>
        <td>
          <% if picture.artwork.pictures.count == 1 %>
            <%= link_to content_tag(:i, nil, class: 'fas fa-trash-alt'), picture.artwork, data: { confirm: "Attention la suppression de cette photo entrainera la suppression de l'oeuvre !" }, method: :delete %>
          <% else %>
            <%= link_to content_tag(:i, nil, class: 'fas fa-trash-alt'), picture, data: { confirm: "Etes-vous sûr(e) ?" }, method: :delete %>
          <% end %>
          <%= link_to content_tag(:i, nil, class: 'far fa-thumbs-up'), unsignal_picture_path(picture) %>
          </td>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/signaledpicturesmoderation.html.erb
<div class="my_header">
  <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), url_for(:back) %> </li>
    </li>
    <div class="header_title">
      <div class="header_title_logo"></div>
    </div>
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-sign-out-alt'), destroy_user_session_path, method: :delete  %>
    </li>
</div>

<div class="body-container">
  <div class="artwork_moderation">
    Modération des images signalées :
  </div>
</div>