config/routes.rb
Rails.application.routes.draw do
  get 'routes/index'

  get 'routes/show'

  root "artworks#index"

  get 'pictures/new'
  get 'pictures/show'
  get 'pictures/create'
  get 'pictures/destroy'



  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show] do
      member do
        put "validated", to: "admin#artists_validated"
      end
  end

	resources :artworks do
    member do
      put "validated", to: "admin#artwork_validated"
    end
  end
	resources :searches
  resources :routes
	resources :pictures do
    member do
      put "like", to: "pictures#upvote"
      put 'unlike', to: "pictures#downvote"
    end
  end

	get 'admin', to: "admin#adminboard", as: "admin"
  get 'admin/artwork-moderation', to: "admin#artwork_moderation", as: "art_moderation"
  get 'admin/new-pictures-moderation', to: "admin#new_pictures_moderation", as: "new_pic_moderation"
  get 'admin/signaled-pictures-moderation', to: "admin#signaled_pictures_moderation", as: "signaled_pic_moderation"
  get 'admin/artists-moderation', to: "admin#artists_moderation", as: "artists_moderation"

	get 'users/:id', to: "users#show", as: "user_profile"
  put 'admin/validates_artist/:id', to: "admin#validates_artist", as: "validates_artist"
  put 'admin/unvalidate_artist/:id', to: "admin#unvalidate_artist", as: "unvalidate_artist"


  get 'artworks/show_small/:id', to: "artworks#show_small"
  get 'artworks/new/:lat/:long', to: "arwtorks#new"
  get 'artworks/claimed/:id', to: "artworks#claim_artwork", as: "claim_artwork"

  get 'pictures/signaled/:id', to: "pictures#signal", as: "signal_picture"
  get 'pictures/moderate/:id', to: "pictures#moderate", as: "moderate_picture"
  get 'pictures/unsignal/:id', to: "pictures#unsignal", as: "unsignal_picture"

  get 'menu/camera_kit'
  get 'menu/technics'
  get 'menu/propos'


end

app/models/artwork.rb
class Artwork < ApplicationRecord
	include AlgoliaSearch

	has_many :pictures, dependent: :destroy
	has_and_belongs_to_many :artists, class_name: "User"
	validates :lat, :long, presence: true
    has_and_belongs_to_many :routes

    reverse_geocoded_by :lat, :long
    after_validation :reverse_geocode

	algoliasearch do

		# list of attribute used to build an Algolia record
    attributes :title, :style, :created_at

    # the `searchableAttributes` (formerly known as attributesToIndex) setting defines the attributes
    # you want to search in: here `title`, `subtitle` & `description`.
    # You need to list them by order of importance. `description` is tagged as
    # `unordered` to avoid taking the position of a match into account in that attribute.
    searchableAttributes ['title', 'style']

    # the `customRanking` setting defines the ranking criteria use to compare two matching
    # records in case their text-relevance is equal. It should reflect your record popularity.

	end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
	before_action :authenticate_user!
  attr_accessor :style, :artist

  def index
  	@artworks = Artwork.all
    @artworks_js = @artworks.to_json(include: [:artists, :pictures])
  end

  def new
  	@artwork = Artwork.new
  end

  def create
  	@artwork = Artwork.new(artworks_params)
  	@artwork.lat = @artwork.lat.to_f
  	@artwork.long = @artwork.long.to_f
  	@artwork.artists << current_user
    @artwork.save

    @last_picture = current_user.pictures.last
    @last_picture.artwork = @artwork
    @last_picture.save

    flash[:notice] = 'Félicitations, vous venez de créer une oeuvre !'

    redirect_to @artwork

  end

  def show
  	@artwork= Artwork.find(params[:id])
  end

  def show_small
    @artwork= Artwork.find(params[:id])
    @artworks = Artwork.all
  end

  def edit
  	@artwork = Artwork.find(params[:id])
  end

  def update
  	@artwork = Artwork.find(params[:id])
  	if @artwork.update(artworks_params)
      if !params[:artists].nil?
      @artwork.artists << User.find(params[:artists])
  		redirect_to @artwork
      end
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@artwork = Artwork.find(params[:id])
  	@artwork.destroy
  	if current_user.admin = true
			redirect_to art_moderation_path
		else
			redirect_to artworks_path
		end
  end

  def claim_artwork
    @artwork = Artwork.find(params[:id])
    current_user.created_artworks << @artwork
    if !current_user.artist
      current_user.status = "pending"
      current_user.save
      flash[:notice] = 'Cette oeuvre apparaîtra sur votre profil après modération !'
    else
      flash[:notice] = 'Cette oeuvre a été ajoutée à votre profil !'
    end
    redirect_to @artwork
  end

	private
	def artworks_params
		params.permit(:title, :description, :lat, :long, :artist, :style)
	end

end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_show_small.html.erb
<div class ="artwork-image-likes">
    <%= link_to cl_image_tag(@artwork.pictures.first.img_url, :secure => true, :width => 200, :height => 200, :crop => :fill), artwork_path(@artwork) %>
</div>

<div class = "artwork-infos">
      <p><i class="fas fa-user"></i>
        <% if @artwork.artists.select{|a| a.status == "validated"}.count > 0 %>
        <% @artwork.artists.select{|a| a.status == "validated"}.each do |artist| %>
          <%= link_to artist.pseudo, user_path(artist) %> &nbsp
            <% end %>
        <% else %>
            <% if @artwork.artist == "" || @artwork.artist.nil?%>
            Artiste non renseigné
            <% else %>
            <%= @artwork.artist %>
          <% end %>
        <% end %>
      </p>
      <p><i class="fas fa-paint-brush"></i>
        <% if @artwork.style.nil? || @artwork.style == "" %>
          Technique non renseignée
        <% else %>
          <%= @artwork.style %>
        <% end %>
      </p>
      <p class="address-artwork"><i class="fas fa-location-arrow"></i>  <%=@artwork.address%> </i></p>
</div>

app/views/artworks/index.html.erb
<% content_for :meta_title, "Creapolis - Accueil" %>

<div class="my_header">

    <li>
      <span style="font-size:30px;cursor:pointer" onclick="openNav()">
        <i class="fas fa-bars"></i>
      </span>
    </li>

    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>

    <!-- Don't remove this empty <li> -->
    <li></li>

    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "À propos", menu_propos_path, class:"nav-item"%>
      <%= link_to "Guide de l'explorateur", menu_camera_kit_path, class:"nav-item"%>
      <%= link_to "Techniques art urbain", menu_technics_path, class:"nav-item"%>
    </div>
</div>



<div class="background-new-form">
</div>

<% if user_signed_in? %>
<div id="map_index"></div>

  <%= render 'layouts/bottom_menu' %>

<!-- if user is not signed_in, he can sign in -->
  <% else %>

  <div class="connection">
    <!-- formulaire pour se connecter -->
    <div class="box-connection-top">
      <%= render "layouts/login" %>

    </div>
    <div class="box-connection-bottom">
          <%= link_to "Créer un compte", new_user_registration_path%>
    </div>
  </div>
</div>
<% end %>


<div class="popup-container" style="display: none">
</div>

<script type="text/javascript">

getLocation();

// This is a public token
if (sessionStorage.getItem('lat') === null) {
  map = L.map('map_index').setView([ 48.866667,  2.333333], 13)
} else {
  map = L.map('map_index').setView([sessionStorage.getItem('lat'),sessionStorage.getItem('lng')], 13)
}

// This is a public token
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g', {
    attribution: '&copy; OpenStreetMap, CC-BY-SA, Imagery © Mapbox',
    maxZoom: 20,
    id: 'mapbox.streets',
    accessToken: 'pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g'
}).addTo(map);

// Activate geoloc
L.control.locate().addTo(map)

// Puts markers on map
var markers_clusters = L.markerClusterGroup({
  disableClusteringAtZoom: 17
});

map.addLayer(markers_clusters);
var arr = <%= @artworks_js.html_safe %>
var markers = {};

// For each marker clicked, we send an AJAX request to show a small version of show artwork
 arr.forEach(function (markerConfig, index) {
  if (arr[index].pictures.length >0){
    marker = new L.Marker([arr[index].lat,arr[index].long]);
    markers_clusters.addLayer(marker);
    marker.on('click', function(){
    $.ajax({
          type: "GET",
          contentType: "application/json; charset=utf-8",
          url: "/artworks/show_small/"+arr[index].id,
      });
    $(".leaflet-control-attribution").hide()
    });
  };
});

// If a user clicks on the map, the show_small of artworks is hidden
 map.on('click', function(){
  $(".popup-container").hide()
  $(".leaflet-control-attribution").show()
 });


//console.log(sessionStorage.getItem('lat'));


//Left side navigation menu
  function openNav() {
      document.getElementById("mySidenav").style.width = "80%";
  }

  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
  }


$('.nav-item').on("click", function(){
  $('#mySidenav').hide();
})

</script>

app/views/artworks/new.html.erb
<% content_for :meta_title, "Creapolis - Ajouter une oeuvre" %>

<div class="my_header">
    <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), new_picture_path %> </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li></li>
</div>

<div class="body-container">
	<div class="artwork-new">
		<p> Faites glisser le marqueur jusqu'à l'emplacement exact de l'oeuvre ! </p>
		<%= form_tag artworks_path(@artwork) do %>
		<% if @artwork.errors.any? %>
		<div id="error_explanation">
		  <h2>
		    <%= pluralize(@artwork.errors.count, "error") %> prohibited
		    this user from being saved:
		  </h2>
		    <% @artwork.errors.full_messages.each do |msg| %>
		      <p><%= msg %></p>
		    <% end %>
		</div>
		<% end %>

		<div id="small-map-index"></div>
		<div id= "move-marker">
			<div id="generate-location" style="display: none">Actualiser mon emplacement</div>
		</div>

		<div class="field input" >
		  <%= text_field_tag :artist, nil, placeholder: "Nom de l'artiste (si vous le connaissez)" %>
		</div>
		<div class="field input">
		  <%= text_field_tag :style, nil, placeholder: "Techniques utilisées par l'artiste" %>
		</div>
		<div class="field input" style="display: none">
		  <%= label_tag 'lat', "Latitude"  %>
		  <%= text_field_tag :lat, id:"lat" %>
		</div>

		<div class="field input" style="display:none">
		  <%= label_tag 'long', "Longitude"  %>
		  <%= text_field_tag :long, id:"long" %>
		</div>
		<%= submit_tag 'Valider', class: "btn btn-primary", id:"submit-artwork"%>
		<% end %>
	</div>
	<!-- <div class="picture-new" style="display: none"> -->
</div>

<script type="text/javascript">

getLocation();

console.log(sessionStorage.getItem('lat') + ", " + sessionStorage.getItem('lng'));

// We start by getting current user location

document.getElementById("lat").value = sessionStorage.getItem('lat');
document.getElementById("long").value = sessionStorage.getItem('lng');



// We set the map where the new point is supposed to be
if (sessionStorage.getItem('lat') === null) {
	console.log("coucou")
	$("#small-map-index").html("Il semblerait que nous n'avons pas réussi à vous géolocaliser :(");
	$("#generate-location").show();
	$("#drag-marker").hide();


} else {

	small_map = L.map('small-map-index').setView([sessionStorage.getItem('lat'), sessionStorage.getItem('lng')], 16)


	// This is a public token
	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g', {
	    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
	    maxZoom: 20,
	    id: 'mapbox.streets',
	    accessToken: 'pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g'
	}).addTo(small_map);

	var marker = L.marker([sessionStorage.getItem('lat'), sessionStorage.getItem('lng')],{draggable: true}).addTo(small_map);

	marker.on("drag", function(e) {
	    var marker = e.target;
	    //console.log(marker._latlng.lat)
	    document.getElementById("lat").value = marker._latlng.lat;
		document.getElementById("long").value = marker._latlng.lng;
	    // small_map.panTo(new L.LatLng(marker._latlng.lat, marker._latlng.lng));
	});
}

$("#generate-location").on("click", function(){
	getLocation();
	window.location.reload();
})





</script>

app/views/artworks/show.html.erb
<% content_for :meta_title, "Creapolis - Oeuvre d'art urbain de #{@artwork.artist}" %>

<div class="my_header">
    <li> <%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), root_path %> </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li></li>
</div>

<!-- body-container begin -->
<div class="body-container">
  <!-- container-fluid -->
  <div class="container-fluid artwork-page">
    <!-- Row content begin -->
    <div class="artwork-vizualisation">
      <br>

      <!-- Class col sm 9 begin -->
      <div class="col-sm-9 col-md-12">

      <!-- Slideshow begin -->
      <% @artwork.pictures.each.with_index do |picture, index| %>
        <div class="mySlides artwork-slideshow">
          <div class="numbertext"><%= index + 1 %> / <%= @artwork.pictures.count %>
          </div>

            <%= cl_image_tag picture.img_url, :secure => true, class: "img-responsive" %>

          <div class="artwork-picture-info">

            <div class="user_avatar_row_small_type">
              <div class="publish space-top-bot-10">
                <%= link_to user_profile_path(picture.user_id) do %>
                  <% if picture.user.profile_picture.url.nil? %>
                  <%= image_tag "default_profile_picture.png"%>
                  <% else %>
                  <%= cl_image_tag picture.user.profile_picture,:width => 200, :height => 200, :crop => :fill, :secure => true %>
                  <% end %>
                <% end %>

                <span style="padding-left: 5px;">
                  Publié par :
                  <span style="font-weight: bold;">
                    <%= link_to user_profile_path(picture.user_id) do %>
                    <%= picture.user.pseudo %>
                    <% end %>
                  </span>
                </span>
              </div>
            </div>

            <div>
              <% if current_user.voted_for? picture %>
                  <%= link_to unlike_picture_path(picture), method: :put, class: "round-corner-ok-small" do %>
                    <i class="fas fa-heart" style="color:#E76262"></i>
                    <span style="font-size: 12px; color:#E76262; font-weight: 700; font-size: 16px;margin-left: 5px;">
                    <%= picture.get_upvotes.size %></span>
                  <% end %>
              <% else %>
                  <%= link_to like_picture_path(picture), method: :put, class: "round-corner-no-small" do %>
                    <i class="far fa-heart"></i>
                    <span style="font-size: 16px;margin-left: 5px;">
                    <%= picture.get_upvotes.size %></span>
                  <% end %>
              <% end %>
            </div>
            <div class="signal-picture-button detail_signal">
              <%= link_to content_tag(:i, nil, class: "fas fa-exclamation-triangle"), signal_picture_path(picture) %>
            </div>
          </div>

        </div>
      <%end%>

      <% if @artwork.pictures.count > 1 %>
        <div class="scroll-group">
          <div class="row">
            <% @artwork.pictures.reverse_each.with_index do |picture, index| %>
              <div class="col-xs-4 col-md-2">
              <%= cl_image_tag(picture.img_url, :crop => :fill, :width => 400, :height => 225, :secure => true, class: "img-responsive demo cursor", :onclick =>"currentSlide(#{index+1})")%>
              </div>
            <%end%>
          </div>
        </div>
      <%end%>
      <!-- Slideshow end -->
      <% if mobile_device? %><!-- Afficher l'ajout d'une image seulement depuis un device mobile -->
        <%= form_tag (pictures_path(id: @artwork.id)), multipart: true do %>
          <div class="add-picture-to-artwork">
            <i class="fas fa-plus-circle fa-2x" onclick="document.getElementById('upload').click();"> </i>
            <p onclick="document.getElementById('upload').click();"> Ajoutez votre photo de cette oeuvre pour la faire apparaître sur votre carte ! </p>
          </div>
          <%= file_field_tag :img_url, id:"upload", style:"display:none", onchange:"readURL(this);" %>
          <div class= "center-picture-preview">
            <img id="picture-preview" alt="your image" style="display:none;" />
          </div>
          <div class="submit-new-picture-button" style="display:none">
            <%= submit_tag 'Valider'%>
          </div>
        <% end %>
      <% end %>
      </div>
      <!-- Class col sm 9 end -->

    </div>
    <!-- Row content begin -->

    <div class="artwork-meta">
      <!-- Artwork info begin -->
      <div class="artwork_info">
        <div class="artwork_info_artist">
          <ul>
            <li><i class="fas fa-user" style="margin-right: 15px;"></i></li>
              <% if @artwork.artists.select{|a| a.status == "validated"}.count > 0 %>
              <% @artwork.artists.select{|a| a.status == "validated"}.each do |artist| %>
                <%= link_to artist.pseudo, user_path(artist) %> &nbsp
                  <% end %>
              <% else %>
                  <% if @artwork.artist == "" || @artwork.artist.nil?%>
                  Artiste non renseigné
                  <% else %>
                  <%= @artwork.artist %>
                <% end %>
              <% end %>
          </ul>
        </div>

        <div class="artwork_info_tech">
          <ul>
            <li><i class="fas fa-paint-brush" style="margin-right: 15px;"></i></li>
            <li><span>
              <% if @artwork.style.nil? || @artwork.style == "" %>
                Technique non renseignée
              <% else %>
                <%= @artwork.style %>
              <% end %>
            </span></li>
          </ul>
        </div>

        <div class="artwork_address">
          <ul>
            <li><i class="fas fa-map-marker" style="margin-right: 15px;"></i></li>
            <li><span>
              <% if @artwork.address.nil? %>
                Pas de lieu renseigné
              <% else %>
                <%= @artwork.address %>
              <% end %>
            </span></li>
          </ul>
        </div>

      </div><!-- Artwork info end -->

      <div class="claim-artwork">
        <% if !current_user.created_artworks.include?(@artwork)%>
          <%= link_to "Je suis l'auteur de cette oeuvre", claim_artwork_path(@artwork) %>
        <%end %>
      </div>
    </div>

  </div>

</div>




<!-- Script slideshow artwork -->
<script type="text/javascript">
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  slides[slideIndex-1].style.display = "block";
}

function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#picture-preview')
        .attr('src', e.target.result)
        .height(200);
    $('#picture-preview').show();
    $(".submit-new-picture-button").show();
    };
    reader.readAsDataURL(input.files[0]);
  }

}

$('#submit-picture').click(
function(){
  if($('#upload').get(0).files.length === 0){
      alert("Vous n'avez pas rentré de photo pour cette oeuvre !");
      return false;
   } else {
    return true;
   }
});


</script>
<!-- Script slideshow artwork -->

app/views/artworks/show_small.js.erb
$('.popup-form').hide()
$('.popup-container').show()
$('.popup-container').html("<%= j (render 'show_small') %>");