config/routes.rb
Rails.application.routes.draw do
  get 'routes/index'

  get 'routes/show'

  root "artworks#index"

  get 'pictures/new'
  get 'pictures/show'
  get 'pictures/create'
  get 'pictures/destroy'



  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show] do
      member do
        put "validated", to: "admin#artists_validated"
      end
  end

	resources :artworks do
    member do
      put "validated", to: "admin#artwork_validated"
    end
  end
	resources :searches
  resources :routes
	resources :pictures do
    member do
      put "like", to: "pictures#upvote"
      put 'unlike', to: "pictures#downvote"
    end
  end

	get 'admin', to: "admin#adminboard", as: "admin"
  get 'admin/artwork-moderation', to: "admin#artwork_moderation", as: "art_moderation"
  get 'admin/new-pictures-moderation', to: "admin#new_pictures_moderation", as: "new_pic_moderation"
  get 'admin/signaled-pictures-moderation', to: "admin#signaled_pictures_moderation", as: "signaled_pic_moderation"
  get 'admin/artists-moderation', to: "admin#artists_moderation", as: "artists_moderation"

	get 'users/:id', to: "users#show", as: "user_profile"
  put 'admin/validates_artist/:id', to: "admin#validates_artist", as: "validates_artist"
  put 'admin/unvalidate_artist/:id', to: "admin#unvalidate_artist", as: "unvalidate_artist"


  get 'artworks/show_small/:id', to: "artworks#show_small"
  get 'artworks/new/:lat/:long', to: "arwtorks#new"
  get 'artworks/claimed/:id', to: "artworks#claim_artwork", as: "claim_artwork"

  get 'pictures/signaled/:id', to: "pictures#signal", as: "signal_picture"
  get 'pictures/moderate/:id', to: "pictures#moderate", as: "moderate_picture"
  get 'pictures/unsignal/:id', to: "pictures#unsignal", as: "unsignal_picture"

  get 'menu/camera_kit'
  get 'menu/technics'
  get 'menu/propos'


end

app/models/route.rb
class Route < ApplicationRecord
  has_and_belongs_to_many :artworks
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
  	@routes = Route.all
  end

  def show
  	@route = Route.find(params[:id])
  	@route_artworks = @route.artworks
    @route_artworks_js = @route_artworks.to_json#(include: { artwork: { only: [:lat, :long]}})
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/index.html.erb
<% content_for :meta_title, "Creapolis - Parcours" %>

<div class="my_header">

    <li>
      <span style="font-size:30px;cursor:pointer" onclick="openNav()">
        <i class="fas fa-bars"></i>
      </span>
    </li>

    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>

    <!-- Don't remove this empty <li> -->
    <li></li>

    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "À propos", menu_propos_path, class:"nav-item"%>
      <%= link_to "Guide de l'explorateur", menu_camera_kit_path, class:"nav-item"%>
      <%= link_to "Techniques art urbain", menu_technics_path, class:"nav-item"%>
    </div>
</div>


<div class="spaceleft">
	<div class="title_routes">Retrouvez tous nos itinéraires Street Art</div>
</div>


<div class="list-group list-special">
<% @routes.each do |route| %>
  <span class="list-group-item">
    <%= link_to image_tag(route.artworks.first.pictures.first.img_url), route_path(route)%>
  	<div class="list-group-item-inside">
  	<%= link_to route.title, route_path(route)%>
	  </div>
  </span>
  <% end %>

</div>



<script>
  //Left side navigation menu
  function openNav() {
      document.getElementById("mySidenav").style.width = "80%";
  }

  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
  }


$('.nav-item').on("click", function(){
  $('#mySidenav').hide();
})


</script>

app/views/routes/show.html.erb
<div class="my_header">
    <li><%= link_to content_tag(:i, nil, class: 'fas fa-chevron-left'), routes_path %>
    </li>
    <div class="header_title">
      <%= link_to image_tag("creapolis_logo_temp.png"), root_path %>
    </div>
    <li>
    </li>
</div>

<div class="background-new-form">
</div>


<div class="body-container">
  <% if user_signed_in? %>

  <div class="route-info">
  	<p> <%= @route.title %></p>
  	<p> Plus d'informations </p>
  </div>
  <div class="go-to-route">
    <a href="https://citymapper.com/directions?endcoord=<%=@route.artworks.first.lat%>%2C<%=@route.artworks.first.long%>&endname=<%=@route.title%>"> Y aller <i class="fas fa-arrow-right fa-1x"></i></a>
  </div>

  <div id="map_index"></div>

  <div class="popup-container" style="display: none">
  </div>

  <%= render 'layouts/bottom_menu' %>

<!-- if user is not signed_in, he can sign in -->
  <% else %>

  <div class="connection">
    <!-- formulaire pour se connecter -->
    <div class="box-connection-top">
      <%= render "layouts/login" %>
      <br><br>
      <%= link_to "Mot de passe oublié ?", new_user_password_path %><br/>
    </div>
    <div class="box-connection-bottom">
          <%= link_to "Créer un compte", new_user_registration_path%>
    </div>
  </div>
  <% end %>
</div>


<div class="form-container">
  <div class="popup-form" style="display: none">
  </div>
</div>

<script type="text/javascript">

getLocation();

var artworks = <%= @route_artworks_js.html_safe %>

map = L.map('map_index').setView([ artworks[0].lat, artworks[0].long], 15)

// This is a public token
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 20,
    id: 'mapbox.streets',
    accessToken: 'pk.eyJ1IjoianVzdGlrcm8iLCJhIjoiY2plbzR6djJnM3RyOTJ4cGszb3hiNGdtcCJ9._gRBjH1x_-nGrj7hD-2i6g'
}).addTo(map);

// Activate geoloc
L.control.locate().addTo(map)

var markers = {};

// For each marker clicked, we send an AJAX request to show a small version of show artwork
artworks.forEach(function (artwork) {

  marker =  new L.Marker([artwork.lat,artwork.long]).addTo(map);
  marker.on('click', function(){
  $.ajax({
        type: "GET",
        contentType: "application/json; charset=utf-8",
        url: "/artworks/show_small/"+artwork.id,
    });
  });
});

// If a user clicks on the map, the show_small of artworks is hidden
map.on('click', function(){
	$(".popup-container").hide()
});


</script>