config/routes.rb
Rails.application.routes.draw do
  get 'routes/index'

  get 'routes/show'

  root "artworks#index"

  get 'pictures/new'
  get 'pictures/show'
  get 'pictures/create'
  get 'pictures/destroy'



  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show] do
      member do
        put "validated", to: "admin#artists_validated"
      end
  end

	resources :artworks do
    member do
      put "validated", to: "admin#artwork_validated"
    end
  end
	resources :searches
  resources :routes
	resources :pictures do
    member do
      put "like", to: "pictures#upvote"
      put 'unlike', to: "pictures#downvote"
    end
  end

	get 'admin', to: "admin#adminboard", as: "admin"
  get 'admin/artwork-moderation', to: "admin#artwork_moderation", as: "art_moderation"
  get 'admin/new-pictures-moderation', to: "admin#new_pictures_moderation", as: "new_pic_moderation"
  get 'admin/signaled-pictures-moderation', to: "admin#signaled_pictures_moderation", as: "signaled_pic_moderation"
  get 'admin/artists-moderation', to: "admin#artists_moderation", as: "artists_moderation"

	get 'users/:id', to: "users#show", as: "user_profile"
  put 'admin/validates_artist/:id', to: "admin#validates_artist", as: "validates_artist"
  put 'admin/unvalidate_artist/:id', to: "admin#unvalidate_artist", as: "unvalidate_artist"


  get 'artworks/show_small/:id', to: "artworks#show_small"
  get 'artworks/new/:lat/:long', to: "arwtorks#new"
  get 'artworks/claimed/:id', to: "artworks#claim_artwork", as: "claim_artwork"

  get 'pictures/signaled/:id', to: "pictures#signal", as: "signal_picture"
  get 'pictures/moderate/:id', to: "pictures#moderate", as: "moderate_picture"
  get 'pictures/unsignal/:id', to: "pictures#unsignal", as: "unsignal_picture"

  get 'menu/camera_kit'
  get 'menu/technics'
  get 'menu/propos'


end

app/views/layouts/_bottom_menu.html.erb
<%if user_signed_in?%>

  <div class="bottom_menu">
      <li class="tab1 <%if root_path == request.fullpath %> selected<%end%>" >
          <%= link_to content_tag(:i, nil, class: 'fas fa-map-marker-alt') + "Carte", root_path %>
      </li>

      <li class="tab2 <%if request.fullpath.include?('/routes') %> selected<%end%>" >
        <%= link_to content_tag(:i, nil, class: 'fab fa-cloudsmith') + "Parcours", routes_path %>
      </li>


      <% if mobile_device? %>
        <!-- Image upload with a form -->
        <li class="tab3 <% if (request.fullpath.include?('/artworks/new') || request.fullpath.include?('/pictures/new')) %> selected <%end%>">

          <%= form_tag (pictures_path(id: "0")), id:"picture-upload-form", multipart: true do %>

          <div class="add-picture-footer">
            <%= content_tag(:i, nil, class: "fas fa-plus", id:"new_artwork", onclick:"document.getElementById('upload').click();") + "Ajouter" %>
          </div>

          <%= file_field_tag :img_url, id:"upload", style:"display:none", onchange:"readURL(this);" %>

          <%= submit_tag 'Valider', class: "btn btn-primary", id:"submit-picture", style:"display:none"%>

          <% end %>

        </li>
      <% end %>

      <li class="tab4 <%if '/searches' == request.fullpath %> selected<%end%>">
        <%= link_to content_tag(:i, nil, class: 'fas fa-search') + "Chercher", searches_path %>
      </li>

      <li class="tab5 <%if request.fullpath.include?('/users') %> selected<%end%>">
        <%= link_to content_tag(:i, nil, class: 'fas fa-user') + "Profil", user_profile_path(current_user)%>
      </li>

  </div>
<%end%>



<script type="text/javascript">

function readURL(input) {
  if (input.files && input.files[0]) {
    $("#picture-upload-form").submit();


  }
}

</script>

app/views/layouts/_login.html.erb
<div class="form-title">Se connecter</div>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.email_field :email, autofocus: true, placeholder:"Adresse email", autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.password_field :password, placeholder:"Mot de passe",autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field remember">
      <%= f.check_box :remember_me ,:as => :hidden%>
    </div>

  <% end -%>

    <%= f.submit "Se connecter" %>
    <div class="facebook-login">
        <%= link_to content_tag(:i, nil, class:'fab fa-facebook-square') + "Se connecter avec Facebook", user_facebook_omniauth_authorize_path %>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118269489-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-118269489-1');
	</script>

    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>

    <meta name="description" content="<%= meta_description %>">

		    <!-- Facebook Open Graph data -->
		<meta property="og:title" content="<%= meta_title %>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<%= request.original_url %>" />
		<meta property="og:image" content="<%= meta_image %>" />
		<meta property="og:description" content="<%= meta_description %>" />
		<meta property="og:site_name" content="<%= meta_title %>" />



    <%= stylesheet_link_tag    'application', media: 'all'%>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,900" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@1/dist/instantsearch.min.js"></script>


  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
      <% flash.each do |message_type, message| %>
        <div class="my_alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/bottom_menu' %>


  </body>
</html>